import { describe, expect, test } from "vitest"
import { EntityPool } from "../src/EntityPool"

describe("EntityPool", () => {
  test("allows entity numbers to be allocated and freed back", () => {
    const pool = new EntityPool()
    expect(pool.alloc()).toBe(0)
    expect(pool.alloc()).toBe(1)
    expect(pool.alloc()).toBe(2)
    expect(pool.alloc()).toBe(3)
    expect(pool.alloc()).toBe(4)
    expect(pool.alloc()).toBe(5)
    expect(pool.alloc()).toBe(6)
    expect(pool.alloc()).toBe(7)
    expect(pool.alloc()).toBe(8)
    expect(pool.alloc()).toBe(9)
    pool.free(5)
    expect(pool.alloc()).toBe(5)
    expect(pool.alloc()).toBe(10)
    expect(pool.alloc()).toBe(11)
    expect(pool.alloc()).toBe(12)
    expect(pool.alloc()).toBe(13)
    expect(pool.alloc()).toBe(14)
    expect(pool.alloc()).toBe(15)
    expect(pool.alloc()).toBe(16)
    expect(pool.alloc()).toBe(17)
    expect(pool.alloc()).toBe(18)
    expect(pool.alloc()).toBe(19)
    pool.free(15)
    pool.free(10)
    pool.free(5)
    expect(pool.alloc()).toBe(5)
    expect(pool.alloc()).toBe(10)
    expect(pool.alloc()).toBe(15)
    expect(pool.alloc()).toBe(20)
  })
})
